### ISSUE TITLE
Don't Worck

### ISSUE THREAD

**Issue by shetos126** [mikeshardmind/autorooms#1]
$ python autorooms.py
Traceback (most recent call last):
  File "autorooms.py", line 1, in <module>
    import discord
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

================================
you can help me

**Comment by mikeshardmind** [comment]
The lib it uses isn't python3.7 compatible.
